#!/bin/sh
#
# $FreeBSD: syncd (gpstat), v1.5 2007/09/30 23:10:55 flood Exp 
#
# PROVIDE: gpstat
# REQUIRE: NETWORKING
#
# Add the following line to /etc/rc.conf to enable gpstat_syncd:
#
# gpstat_syncd_enable="YES"
#

gpstat_syncd_enable="${gpstat_syncd_enable-NO}"
. /etc/rc.subr


name=gpstat_syncd
rcvar=`set_rcvar`

prefix=/home/gpstat
procname=gpstat-syncd
pidfile=/var/run/gpstat/syncd.pid
required_files="${prefix}/redefine.conf"
command="${prefix}/bin/syncd"

load_rc_config ${name}

run_rc_command "$1"
